name: Test Server Merge
on:
  push:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3

      - name: Set application.properties from secrets
        run: |
          echo "${{ secrets.TEST_APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: remove plain.jar
        run: rm -rf build/libs/*plain.jar

      #      - name: file copy
      #        uses: actions/upload-artifact@v3
      #        with:
      #          name: libs
      #          path: build/libs
      #  deploy:
      #    needs: build
      #    runs-on: ubuntu-latest
      #    steps:
      #      - name: file download
      #        uses: actions/download-artifact@v3
      #        with:
      #          name: libs
      #          path: libs
      - name: Upload to Cloudflare
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CF_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          BUCKET_NAME: ${{ secrets.CF_BUCKET_NAME }}
          ENDPOINT_URL: ${{ secrets.CF_ENDPOINT_URL }}
        run: |
          aws s3 sync build/libs/ s3://$BUCKET_NAME/java/main/boss \
            --endpoint-url $ENDPOINT_URL --delete --exact-timestamps

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_SSH_KEY }}
          port: ${{ secrets.TEST_PORT }}
          timeout: 40s  # 30초 기본
          script: |
            aws s3 sync s3://readyvery-dev-server/java/main/boss ./docker/java/boss/jar \
            --endpoint-url https://29c6e4b55b1ddb8d2b6e69df21141caa.r2.cloudflarestorage.com \
            --delete --exact-timestamps
            
            docker-compose build java-boss
            docker-compose up -d java-boss

      - name: Discordbot alert         # 디스코드 알림
        uses: sarisia/actions-status-discord@v1.13.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: ${{ (github.actor == 'marinesnow34' && '<@392607023495118862>') ||
            (github.actor == '1223v' && '<@368775981667844098>') ||
            (github.actor == 'imi21123' && '<@999337351799128115>') ||
            (github.actor == 'marina-yhm' && '<@946431150614794240>') ||
            (github.actor == 'hhhhyelim' && '<@1076887091427946496>') }}
        if: always()
